[package]
name = "anti-loneliness-solana-dapp"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
num-bigint ={ version="0.4.6", features = ["rand"] }
rand = "0.8.5"
solana-sdk = "2.0.13"
tokio = {version="1.40.0", features = ["rt", "rt-multi-thread", "tokio-macros", "net", "macros"]}
